set hive.server2.logging.operation.level=NONE;

DROP TABLE IF EXISTS ${DEST_DB}.ctr_comp_score_flow_plus_atr;

CREATE TABLE ${DEST_DB}.ctr_comp_score_flow_plus_atr
STORED AS PARQUET AS
SELECT
	infocheck_id,
	informconf_id,
	pers_id,
	tipo_doc_id,
	inf_conv_cant_abiertas,
	inf_dem_cant_total,
	inf_dem_cant_total_cable,
	inf_dem_cant_total_ccredito,
	inf_dem_cant_total_comercio,
	inf_dem_cant_total_sf,
	inf_dem_cant_total_spub,
	inf_dem_cant_total_telco,
	inf_inc_cant_abiertas,
	inf_inhib_cant_abiertas,
	inf_mor_cant_total,
	inf_mor_cant_total_cable,
	inf_mor_cant_total_ccredito,
	inf_mor_cant_total_sf,
	inf_mor_cant_total_spub,
	inf_mor_cant_total_telco,
	inf_qui_cant_abiertas,
	inf_rem_cant_abiertas,
	scorecard,
	ich_ch_re_cant_i_fond,
	ich_cons_cant_total,
	ich_cons_cant_banco_admin,
	distrito,
	edad,
	estado_civil,
	cast(null as string) sexo,
	ich_fecha_ult_cons_priv,
	ips_flag_actividad,
	max_flow,
	g_max_venc_ten_36,
	inf_cant_dist_afi_u6m,
	inf_cant_dist_afi_ccred_u3m,
	inf_cant_dist_afi_telco_u12m,
	inf_cons_cant_telco_u1m,
	inf_cons_cant_total_telco,
	inf_cons_cant_u1m,
	inf_cons_ult_dias_ccredito,
	inf_cons_ult_dias_sf,
	inf_morce_cant_31_45_abiertas,
	inf_morce_cant_46_60_abiertas,
	inf_morce_cant_61_90_abiertas,
	inf_morce_cant_abiertas,
	p_cant_atraso,
	p_saldo_vencido_ult_act,
	p_sdot_monto_gt75_m1,
	situacion_bancaria,
	tc_close_total,
	tc_max_dias_atraso_u6m,
	tc_primera_act,
	tc_prom_pmin_limcr_m1,
	tc_svenc_sdot_gt0_u12m,
	fecha_obs,
	score_pos,
	flow_pos,
	${ARCHV} as archv,
	from_unixtime(unix_timestamp()) as time_stamp
from ${SOURCE_DB}.ctr_comp_score_flow_plus_atr;